<?php
session_start();
date_default_timezone_set("Asia/Bangkok");
include("inc_head.php");
include("connection.php");
include("logindata.php");
include("./dashboard/setting/edit.php");
include("swal.php");
?>